### ISSUE TITLE
1 to 1 mapping

### ISSUE THREAD

**Issue by Vanuan** [IFSight/d4m-nfs#12]
Currently it is suggested to use /mnt path in xhyve. Wouldn't it be possible to use /Users, etc? So that peoople wouldn't need to change their docker-compose files.

AFAIK, Docker has an option to prevent /Users directories from being mounted.

**Comment by if-kenn** [comment]
Please see the README

**Comment by Vanuan** [comment]
Are you saying it's impossible?

**Comment by if-kenn** [comment]
No, it is possible:

> You can now specify what mounts you want in the d4m-nfs-mounts.txt file. Note that if you do this, you need to make sure that it does not conflict with D4M settings, in other words if you want to have /Users be served by NFS instead of osxfs you will need to remove it from the D4M Preferences -> File Sharing. The /tmp share must stay since that is how d4m-nfs exchanges information with the D4M Moby VM.

**Comment by Vanuan** [comment]
Ah, great.
