### ISSUE TITLE
Mounting a single file

### ISSUE THREAD

**Issue by shankie-codes** [IFSight/d4m-nfs#13]
This is really great stuff. I'm having trouble mounting a single file (rather than an entire directory). I can work around it as my directory only contains one file (so I can volume-map in the directory). So I'm not in a great rush, but this would be great!

**Comment by if-kenn** [comment]
If you are trying to put one file into the d4m-nfs-mounts.txt file, then it would explain why it is not working. NFS along with many other file systems need to mount directories. Docker on the other hand allow you to mount just files. What you would want to do is put the parent directory of the file you want to mount in d4m-nfs-mounts.txt and in your compose or docker command line use the explicit file.

**Comment by shankie-codes** [comment]
No, it's a mount specified in my `docker-compose.yml`, like this:

```
  volumes:
    - ./http_config:/var/lib/nginx-conf/default.conf.erb
```

I'll work around it by mounting the parent directory – no problem for me, I just thought it would be worth noting.

Thanks!
