### ISSUE TITLE
echo commands in script are not working as expected

### ISSUE THREAD

**Issue by genei09** [IFSight/d4m-nfs#14]
on initial run the script places a line in the /etc/exports file that causes it to error:
-e # d4m-nfs exports

after removing the -e from the file
during the run several more echos of -e and -n are seen.

Ultimately nothing is mounted into the Alpine VM, but the directory names are seen of what I attempted to specify in the file

**Comment by if-kenn** [comment]
Something sounds odd about your shell environment that others are not seeing. Those "-e" are a switch for bash echo to enable interpretation so that things like "\n" can be used.

**Comment by genei09** [comment]
I haven't done anything special to the shell environment.
example output after removing etc/d4m-nfs-mounts.txt

```
sh d4m-nfs.sh 
Copy the Moby VM APK Cache back
Create the script for Moby VM
-e Start and restop nfsd, for some reason restart is not as kind.
Stopping the nfsd service (use 'disable' to make permanent)
Starting the nfsd service
-n Wait until NFS is setup.
-n .
-ne 
Wait until D4M is running.
-e 
Copy back the APK cache



cp: /tmp/d4m-apk-cache/*: No such file or directory
```

**Comment by genei09** [comment]
using the d4m-nfs-mount.txt file or not, I see nothing from the OSx FS in the Alpine VM

**Comment by if-kenn** [comment]
Please call it like ./d4m-nfs.sh you are effecting the environment by having it in another shell.

**Comment by genei09** [comment]
I had to restart d4m a few times and rerun the script a few times but eventually it started working. 

Thanks!

**Comment by if-kenn** [comment]
Great to hear it is working!

Probably re-running it a few times help clear out hung networking. I am going to close out this issue.
