### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by mrfelton** [IFSight/d4m-nfs#15]
Hi,
I have this working (and it works very well, thanks!) when using an absolute path to for the volume mount source (eg, `/mnt/workspace/example/app:/app`). The problem with this though is that with this absolute path my docker-compose file is now not portable - it's completely specific to my machine.

Usually I would use relative paths to the local source (eg, `./app:/app`) to mount my sourec code into a container.

Is there a way that this can be made to work with relative paths so that we can keep our docker-compose files portable and reusable?

**Comment by if-kenn** [comment]
Please see: https://github.com/IFSight/d4m-nfs/issues/5
