### ISSUE TITLE
how to clean up nfs?

### ISSUE THREAD

**Issue by realmtian** [IFSight/d4m-nfs#20]
First of all, I really appreciate this repository as it helps a lot when mounting volumes on mac docker.

In the future, if I decide to abandon this approach. What should I do to clean up what have done by the `d4m-nfs.sh` script?

I noticed it creates some files in `/tmp` and `/etc` and also setup screen and Moby VM. How should I clean them all?

**Comment by if-kenn** [comment]
I hope we will all stop using this utility someday when Docker for Mac makes their osxfs implementation usable :).

For cleaning up files, when you want to stop using it, you would want to just blank out /etc/exports file which , and rebooting your Mac removes files from /tmp.
