### ISSUE TITLE
Eternal "Wait until D4M is running....."

### ISSUE THREAD

**Issue by pensiero** [IFSight/d4m-nfs#3]
With the latest version of _Docker for Mac_ beta (release `Version 1.12.3-rc1-beta29 (13397)`), when I start the script it says

```
Start and restop nfsd, for some reason restart is not as kind.
Stopping the nfsd service (use 'disable' to make permanent)
Starting the nfsd service
Wait until NFS is setup..
Wait until D4M is running......
```

and it never end. Docker for Mac is running. What could be?

**Comment by brianvice** [comment]
It seems that docker is registering it's running vmstate differently in newer beta releases? To remedy this issue for the time-being until the repo owner can address it you can comment out the lines that check to see if d4m is running.  (line 46-50)

**Comment by pensiero** [comment]
Thanks @brianvice

**Comment by pensiero** [comment]
Should I leave this issue open?

**Comment by brianvice** [comment]
@pensiero The issue isn't really resolved I think. I don't know if it's necessary to check that the docker vm has started before continuing the script commands. Although It seems that since the script starts docker it is clear that it is running so another check might not be necessary.  Just my two cents

I have noticed that this resolves my performance issues with docker native for macos. Thanks very much to the developer!

**Comment by pensiero** [comment]
Quote, it's incredibly fast now

**Comment by brianvice** [comment]
The issue isn't really resolved I think. I don't know if it's necessary to check that the docker vm has started before continuing the script commands. Although It seems that since the script starts docker it is clear that it is running so another check might not be necessary.  Just my two cents

**Comment by if-kenn** [comment]
The reason you thought you could just comment it out was that D4M was probably already running and not being opened by d4f-nfs. So if it wasn't running already it probably wouldn't work.

I think I have made it D4M compatible with both stable and beta by running the miniscule docker image hello-world. You can delete this container, but if you do it will prevent d4m-nfs to be able to run offline.

Please let me know if this fixes your problem so if I can close this issue.

Thanks!

**Comment by pensiero** [comment]
YES! Now it works! Good job @if-kenn
