### ISSUE TITLE
Persist mounts when Docker restarted

### ISSUE THREAD

**Issue by pszalko** [IFSight/d4m-nfs#30]
d4m-nfs works great for me when I follow instructions provided in README.

However, the mounts are valid only until Docker is restarted.
Is there any way to make mounts in Docker persist after restart? 
Or is there a way to make Docker to mount nfs resources automatically after started?

Thanks!

**Comment by if-kenn** [comment]
@pszalko You need to use d4m-nfs to restart Docker, since it needs to setup the mounts for you.

**Comment by pszalko** [comment]
@if-kenn I get current solution, thanks.

However, is there a way to make Docker mount nfs resources automatically?

Use case scenario:
1. Computer is restarted.
2. After computer is started again, Docker starts automatically but nfs resources are not mounted.
3. User needs to run d4m-nfs script.

I'm looking for a way to remove step 3. as requirement to use Docker with nfs.

**Comment by if-kenn** [comment]
@knorby @ IFTTT has a PR for this very thing (https://github.com/IFSight/d4m-nfs/pull/29). I have not had the time since it was submitted to look at it. Once I do that should hopefully achieve what you want, but I cannot vouch for it at this time.

**Comment by pszalko** [comment]
Looking forward to have it merged to master, thanks!

**Comment by TomKeur** [comment]
@pszalko It's merged. So I think this Issue can be closed?

**Comment by pszalko** [comment]
Sure! Thanks!
