### ISSUE TITLE
Writes are extremely slow

### ISSUE THREAD

**Issue by ykim** [IFSight/d4m-nfs#31]
I got this up and working correctly on OS X Sierra 10.12.2 on 1.13.0, but writes are really slow compared to the native filesystem. Read appears to be working and definitely faster than the native filesystem. Has anyone else encountered this, or know of a solution?

**Comment by if-kenn** [comment]
@ykim sorry but this is far from enough information to try and provide any help. Please read the README on the home of this repo to make sure you provide *all* information before submitting an issue.

**Comment by ykim** [comment]
I figured it out. It looks like I needed a reboot.
