### ISSUE TITLE
Not allowed to stop the nfsd service on Mac OS 10.12.4

### ISSUE THREAD

**Issue by hovsater** [IFSight/d4m-nfs#43]
When running the `install.sh` script, I get the following error:

```
[d4m-nfs] Start and restop nfsd, for some reason restart is not as kind.
Stopping the nfsd service (use 'disable' to make permanent)
/System/Library/LaunchDaemons/com.apple.nfsd.plist: Operation not permitted while System Integrity Protection is engaged
```

Any ideas on how to solve this?

**Comment by if-kenn** [comment]
@KevinSjoberg the install.sh was a Pull Request from the IFTTT team, so we have little knowledge about it. Sorry but it is not something in my domain of knowledge. A quick Google on your error points to ways to help.

**Comment by hovsater** [comment]
@if-kenn the same problem is present in the `d4m-nfs.sh` script as well.

**Comment by if-kenn** [comment]
It looks as though this might be cause by the new Apple update https://support.apple.com/en-us/HT207615 I have not updated yet and am not seeing it. I will look into it further.

**Comment by if-kenn** [comment]
Here is more info: https://clburlison.com/10.12.4-locationd/

**Comment by if-kenn** [comment]
@KevinSjoberg I was able to fix this issue, please pull and try again.

**Comment by hovsater** [comment]
@if-kenn seems to be working now. Thanks! 👍
