### ISSUE TITLE
ENH: add `mkrakauer-rio/disable-full-sync-on-flush.sh` to start up process.

### ISSUE THREAD

**Issue by davidjeddy** [IFSight/d4m-nfs#50]
`Docker for Mac - Disable full disk sync on flush`: https://gist.github.com/mkrakauer-rio/e7d9de75f5ac680e790365748ca188a4

**Comment by if-kenn** [comment]
@davidjeddy sorry, this needs much more information than a simple gist. The gist itself is also not explanatory enough, for example, looking at a few Docker for Mac implementations I cannot find the reference directory `~/Library/Containers/com.docker.docker/Data/database/disk`.

**Comment by davidjeddy** [comment]
@if-kenn not a problem, I was in a bit of a rush yesterday.

What this does is disabled full disk cache flushing; by doing so it has a positive impact on performance concerning disk read/write.

For example importing a sql dump file. Now instead of flushing the disk between each operation the daemon flies right through it like nobodies business.

The Gist does this by altering some default configuration flags buried in the com.docker.driver configuration files.

**Comment by davidjeddy** [comment]
Any movement on integrating this as part of the startup process?

**Comment by if-kyle** [comment]
No, unlikely to happen anytime soon as we hope docker for mac will just improve the speed of their mounting.

**Comment by davidjeddy** [comment]
Understood, TY. Closing.
