### ISSUE TITLE
d4m doing weird things in my console

### ISSUE THREAD

**Issue by raphaelbadia** [IFSight/d4m-nfs#51]
Hello,
When I turn on my laptop and open a terminal, something really weird happens: it looks like d4m-nfs is running itself in a loop... problem: I didn't even start it !

Click to see the video instead of the gif
[![Click to see a video of the problem](http://g.recordit.co/2W69xmA6h6.gif)](http://recordit.co/2W69xmA6h6)

How do I turn this off? It is really disturbing
Thank you

**Comment by if-kyle** [comment]
Have you checked your various home folder dot files, such as .bash_rc, .bash_profile and see if you have anything auto launching?  d4m-nfs does not auto launch any items with a normal install.

**Comment by if-kenn** [comment]
@RaphaelBadia I believe that this must be related to how you implemented d4m. The information that you provided is actually a program that is run in the Docker Moby VM. The message you are seeing is output from the screen command that connects to that VM. It is not actually "running" on your terminal, just outputting.

**Comment by raphaelbadia** [comment]
Hello,
I implemented d4m using install.sh.
I ran `screen -r d4m` and saw this ![](http://i.imgur.com/jY5m01z.png)
I created the missing file, copying it from /tmp/d4m-nfs/d4m-mount-nfs.sh.
now it's like that ![](http://i.imgur.com/cxz6peP.png)

Howver I still get an error when trying to run my company's project:
`ERROR: for mysql_container  Cannot start service mysql_container: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"custom-my.cnf\\\" to rootfs \\\".....\\\" at \\\".....\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

Honestly, I don't know much about docker and I don't want to bother you with my problems as I feel it's not d4m's fault. I will reinstall it from scratch with help from a senior dev from my company.

 Can you just tell me how to uninstall d4m the right way ?
I removed it from /tmp/ and /opt

Thank you for helping me 👍

**Comment by raphaelbadia** [comment]
I put my `d4m-nfs-mounts.txt` in `/etc/d4m-nfs-mounts.txt` instead of `D4M_FOLDER/etc/d4m-nfs-mounts.txt`
