### ISSUE TITLE
Issue with webpack

### ISSUE THREAD

**Issue by Atala** [IFSight/d4m-nfs#54]
Hey,

I am using `d4m-nfs` with a Symfony (PHP) project that uses webpack to build assets. The FS events are sent fine I think (the recompiling is triggered), but webpack doesn't seem to be able to access the modified file (maybe permission issue?) :
`Module build failed: Error: EIO: i/o error, open '/srv/coopcycle/js/app/cart/Cart.jsx'`

It compiles well if I stop/start my webpack container.

Any idea on how I might debug that?

**Comment by if-kyle** [comment]
Sorry we missed this ticket.  Did you solve the problem?  If not can you please provide the information from https://github.com/IFSight/d4m-nfs#opening-github-issues

**Comment by Atala** [comment]
Sorry I don't have time to reproduce on it right now. I will in the future if some time appears.

Thanks for your message and the project :)
