### ISSUE TITLE
Script will fail if my home directory is not standard

### ISSUE THREAD

**Issue by indapublic** [IFSight/d4m-nfs#58]
Early I moved home directory to another volume (e.g. `/Volumes/Data/username`)
But your script expecting that my directory located inside `/Users/username` and `/cat/exports` contain invalid folder after script execution

**Comment by if-kyle** [comment]
Have you tried making a symlink to of the standard location to the modified location?

**Comment by indapublic** [comment]
@if-kyle Yes, script will always wait for end of script execution in that case...

**Comment by indapublic** [comment]
Created new account with standard path and tried again. Still same behaviour:

> [d4m-nfs] Waiting until d4m-nfs setup is done..

How long I should wait?

**Comment by if-kyle** [comment]
What version of docker are you using?   You should only have to wait a minute or so at the most.

**Comment by indapublic** [comment]
Version 17.12.0-ce-mac49 (21995)

Waited for 15 minutes

**Comment by if-kyle** [comment]
Please see the README of this repo:

https://github.com/IFSight/d4m-nfs

**Comment by indapublic** [comment]
Ooooops. Sorry. Missed LARGEST text in readme :(
