### ISSUE TITLE
fsevents / inotify

### ISSUE THREAD

**Issue by Vanuan** [IFSight/d4m-nfs#9]
If this is a custom script anyway, would it be possible to integrate filesystem notifications?

**Comment by if-kenn** [comment]
Without further information it would be hard for me to answer this.

If you are asking for me to bundle in fsevents / inotify into d4m-nfs, then no, I don't want to do that in order to keep it to the simplest it can be.

On the other hand, I have thought about adding "post run" scripts that can be run in the moby VM or Mac after things are setup, so that might work for you.

**Comment by mrfelton** [comment]
This would be super useful as it would enable us to run a local development environment in watch mode (restarting servers, recompiling code etc on file change) with near native performance using this setup.

**Comment by yvess** [comment]
I have written a sublime text plugin which triggers a file touch in the xhyve vm on file saving. This enables auto reload, recompiling with sublime text. see https://github.com/yvess/sublime_d4m. I'm using the d4m screen session for this.

**Comment by if-kenn** [comment]
@yvess that is a great solution!

**Comment by if-kyle** [comment]
@yvess cool, added a link from the d4m README

**Comment by yvess** [comment]
you can now install sublime_d4m with sublime package control, just enter d4m

**Comment by darwinwu13** [comment]
do you have any solution for Webstorm IDE ?

**Comment by if-kyle** [comment]
@darkeus We are not aware of anyone that has written this for Webstorm.

**Comment by darwinwu13** [comment]
@if-kyle i see, but i am using webstorm to code my React Application, so i need the inotify fsevents to notify webpack so it can auto compile, i just don't know how to add "post run" script like @if-kenn  said

**Comment by if-kenn** [comment]
We are officially deprecating this project. We will leave it in place in case it can [help some people migrate to NFS volumes from the command line or compose](https://github.com/IFSight/d4m-nfs/issues/55#issuecomment-377884136).
